### ISSUE TITLE
Implement cell type

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/nballerina#1048]
**Description:**
$subject.

**Comment by jclark** [comment]
Formula is
![Lemma5_4](https://user-images.githubusercontent.com/499966/182999354-13a1d927-b61e-49e7-8988-27c890087009.jpg)

**Comment by jclark** [comment]
It seems there's a problem with recursive types involving locations.

Consider a type R defined by

```
type R record {| R x; |};
```

This will desugar into an internal location type `type R = { &R x; };`. But when we try to determine whether R is empty, we will recursively call isEmpty on R (because `&R` is empty).  The memoization logic will then treat R as empty.

Note that values belonging to the type can be created e.g.

https://github.com/ballerina-platform/nballerina/issues/1041#issuecomment-1206119659

so it should not be treated as empty.
