### ISSUE TITLE
Remove support for `readonly` in types module

### ISSUE THREAD

**Issue by lochana-chathura** [ballerina-platform/nballerina#1058]
This would involve

- getting read of RO/RW uniform type pairs for selectively immutable basic types
- renaming "uniform" type to "basic" type
- renaming some functions ending with "Rw" to remove the "Rw"
- renumbering the uniform types

**Comment by jclark** [comment]
We want to design the renumbering, so that we can easily compute from the number when a basic type is

- always immutable (e.g. int)
- always mutable (e.g. future)
- selectively immutable (e.g. list)

If we don't have gaps, then the obvious ordering is:

```
NIL = 0x0
BOOLEAN
INT
FLOAT
DECIMAL
STRING
ERROR
TYPEDESC
HANDLE
FUNCTION = 0x9
FUTURE = 0xA
STREAM = 0xB
LIST = 0xC
MAPPING
TABLE
XML
OBJECT
CELL = 0x11
```

Then basic type b is

- always immutable if `b <= 0x9`
- always mutable if `(b & 0x1E) == 0xA`
- selectively immutable if `b >= 0xC`
