### ISSUE TITLE
Compile to native image with GraalVM

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#1082]
See if we can compile nballerina using the support for GraalVM that is being worked on by jBallerina team.

**Comment by jclark** [comment]
We could potentially make nBallerina available for download as an 64-bit Intel Linux binary.

**Comment by jclark** [comment]
Ideally we want a native image that links with LLVM. One way is to compile our JNI version with GraalVM. See https://www.graalvm.org/22.1/reference-manual/native-image/JNI/

Is there any other way?

**Comment by heshanpadmasiri** [comment]
@jclark I did manage to compile our JNI version with GraalVM in such a way that it passes all the tests except

1. [12-narrow/if21-v.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/12-narrow/if21-v.bal)
2. [14-bug/loopassign-v.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/14-bug/loopassign-v.bal)

In both cases, I get a segmentation fault [at this line](https://github.com/ballerina-platform/nballerina/blob/b349ae2f4540b260650271f7891403dae012c370/runtime/balrt.h#L632). When I check the llvm-ir files

**Comment by heshanpadmasiri** [comment]
@jclark I managed to compile our JNI version such that it passes all the tests except for 
1. [12-narrow/if21-v.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/12-narrow/if21-v.bal)
2. [14-bug/loopassign-v.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/14-bug/loopassign-v.bal)

In both cases, I get a segmentation [fault at this line](https://github.com/ballerina-platform/nballerina/blob/b349ae2f4540b260650271f7891403dae012c370/runtime/balrt.h#L632). It seems to me that, we are calling `_bal_tagged_to_float` even when the type check for `float` fail in both of these cases (In fact if I return a dummy value there if the tag of `p` I don't get the segfault). For example, in 14-bug/loopassign-v.bal we call it just before returning void

1. [llvm ir generated using print.llvm](https://gist.github.com/heshanpadmasiri/5393bf4641e8770c757197efb9959587#file-loopassign-v-ll-L48)
2. [llvm ir generated using jni.llvm](https://gist.github.com/heshanpadmasiri/5393bf4641e8770c757197efb9959587#file-loopassign-v-o-ll-L41)

Somehow (My guess is this has to do with how we generated object files) it seems to cause a segfault only in the case of jni. Is this (calling `_bal_tagged_to_float` there) the expected behavior?

**Comment by heshanpadmasiri** [comment]
> @jclark I managed to compile our JNI version such that it passes all the tests except for
> 
> 1. [12-narrow/if21-v.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/12-narrow/if21-v.bal)
> 2. [14-bug/loopassign-v.bal](https://github.com/ballerina-platform/nballerina/blob/main/compiler/testSuite/14-bug/loopassign-v.bal)
> 
> In both cases, I get a segmentation [fault at this line](https://github.com/ballerina-platform/nballerina/blob/b349ae2f4540b260650271f7891403dae012c370/runtime/balrt.h#L632). It seems to me that, we are calling `_bal_tagged_to_float` even when the type check for `float` fail in both of these cases (In fact if I return a dummy value there if the tag of `p` I don't get the segfault). For example, in 14-bug/loopassign-v.bal we call it just before returning void
> 
> 1. [llvm ir generated using print.llvm](https://gist.github.com/heshanpadmasiri/5393bf4641e8770c757197efb9959587#file-loopassign-v-ll-L48)
> 2. [llvm ir generated using jni.llvm](https://gist.github.com/heshanpadmasiri/5393bf4641e8770c757197efb9959587#file-loopassign-v-o-ll-L41)
> 
> Somehow (My guess is this has to do with how we generated object files) it seems to cause a segfault only in the case of jni. Is this (calling `_bal_tagged_to_float` there) the expected behavior?

We can reproduce the same problem with the normal build (ie. one using `print.llvm`) if we we disable clang optimizations.

**Comment by jclark** [comment]
Try using valgrind on the generated llvm.print executable.

Is the double being accessed static data or on the heap?

Check the alignment of the address.

**Comment by heshanpadmasiri** [comment]
[Valgrind log without optimisations (ie. `-CFLAGS=-O0`)](https://github.com/ballerina-platform/nballerina/files/9967029/no-opt.log)

[Valgrind log with optimsations (default which uses `-CFLAGS=-O2`)](https://github.com/ballerina-platform/nballerina/files/9967042/opt.log)

**Comment by heshanpadmasiri** [comment]
As far as I can understand what it (`_bal_tagged_to_float`) try to access is an immediate int (`8`). But since all floats are suppose to be on the heap I can think `_bal_tagged_to_float` assumes it is to be an address in the heap.

**Comment by jclark** [comment]
Looks like there's a bug in our backend somewhere. I guess there's an invalid read which is usually getting optimized away.

**Comment by manuranga** [comment]
[moved](https://github.com/ballerina-platform/nballerina/issues/1114#issuecomment-1310278021)

**Comment by jclark** [comment]
Can we discuss this in #1114?
