### ISSUE TITLE
Invalid record subtype relation

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#1201]
**Description:**
Fallowing semtype test is failing (we are getting `T74 <> T749`)
```
type T74 record {|
    65 X;
|};

type T75 record {|
    int:Signed8 X;
|};

// @type T74 < T749
type T749 T315|T75;

type T315 record {|
    int:Signed8 a;
|};
```
**Additional observations:**
1. Moving definitions of `T74` and `T75` to the bottom of file fixes this. Therefore I assume this has something to do with memoization (AFAIK semtype tests compare all type definitions in the order they appear so I assume comparing `T74` and `T75` at the beginning and memoizing them is probably has some effect on this. Also note that it still gets `T74 < T75` correct)
2. This seems to be a regression bug introduced with b08f01e
3. It seems `T749` must be a union of record types (note with different field name with `T75` and `T74`)

**Comment by manuranga** [comment]
https://github.com/ballerina-platform/ballerina-release/pull/2337 should be reverted once this is fixed.

**Comment by lochana-chathura** [comment]
It turned out the bug was not related to memoization. The culprit is `mappingInhabited()`. 

In the two cases where `T74` and `T75` are at the bottom [1] vs the top [2], we have the same `posList` with a single atom for `T74` and `negList` with two atoms for `T75`, `T315`. However, the `negList` order is different in the two cases. 

- In case [1] (which gives the correct result):

posList: `T74`, negList: `T75`, `T315`
In the first round at `mappingInhabited()`, `T74` gets canceled out by the `T75` thus exiting early saying mapping formular is empty.

- In case[2] (which gives the wrong result):

posList: `T74`, negList: `T315`, `T75`
In the first round at `mappingInhabited()`, `T74` does not get canceled out by the `T315` thus it goes for another round. In this logic, we go back and forth for negAtom being `T315` and  `T75` eventually resulting in the wrong result.

**Comment by lochana-chathura** [comment]
In the case[2], `mappingInhabited()` turned to be behaved as intended. However, the problem seems to be caused by the pairing. 

In the initial sample, replacing "X" with "x" gets the test passed.  

For `record {| T a; 65 X; |}` and `record {| int:Signed8 X; |}` pairing algorithm returns following in its first iteration,
- name: `"X"`
- posType: `T`
- negType: `int:Signed8`

The reason is it expects the record fields to be in sorted ascending order.

**Comment by jclark** [comment]
Record types are supposed to be normalized by sorting the field names, since field order shouldn't affect the type.

**Comment by lochana-chathura** [comment]
> [ballerina-platform/ballerina-release#2337](https://github.com/ballerina-platform/ballerina-release/pull/2337) should be reverted once this is fixed.

Reverts with ballerina-platform/ballerina-release#2339
