### ISSUE TITLE
Implement LLVM instructions needed for `any[]`

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#155]
For #135, we will need:

- ability to create array types (i.e. LLVMArrayType)
- getelementptr with multiple arguments

**Comment by jclark** [comment]
We are going to need `inbounds` on GEP also.  The full GEP is quite complicated, particularly getting the types right.

@heshanpadmasiri Please be sure to test the complicated examples at https://llvm.org/docs/LangRef.html#getelementptr-instruction to make sure the types are right and that LLVM accepts what you're generating.

**Comment by heshanpadmasiri** [comment]
@jclark for array type I am planning on adding following

1. New public type `ArrayType` and public function `arrayType(Type ty, int ElementCount) returns ArrayType` similar to `StructureType` ([`LLVMArrayType`](https://llvm.org/doxygen/classllvm_1_1ArrayType.html))
2. New public function `ConstArray(IntType ty, int[] values) returns Value` (I am assuming currently we need only integers here) ([`LLVMConstArray`](https://llvm.org/doxygen/group__LLVMCCoreValueConstantComposite.html#ga1d0b985a92eb99f65e9bc4e1984ea800))

For `GEP` I’ll change the current function signature to `function getElementPointer(PointerValue ptr, Value[] indices, boolean inbound=false,string? name = ()) returns PointerValue` . I am thinking of adding boolean argument `inbounds=false` instead of creating two separate functions (similar to how we use a single `ret`). ([`LLVMBuildGEP`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gaf392c575dd594d83894d3e71a520ffa4), [`LLVMBuildInBoundsGEP`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gae4f1ccf18cdf461af2e5d36178464d80)). (I am also assuming we can use this method without needing a separate [`LLVMBuildStructGEP`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga1b32ff7050adcbb9debfdf1a9fb9efd6))

**Comment by jclark** [comment]
The function should have been called getElementPtr not getElementPointer, since our naming convention are using the LLVM instruction name with additional capitalization.

Better to make the argument: `"inbounds"? inBounds = ()`. This make the call more readable.

I don't think I need constArray for subset 3. We will need it eventually, but we'll need pointers too.

**Comment by jclark** [comment]
@heshanpadmasiri Unless you are nearly finished with this, could you do a pull request for the easy bit first? i.e.

* add arrayType
* change name and declaration  of getElementPtr, but panic if it has more than one index
