### ISSUE TITLE
Add `LLVM` support for `nsw` arithmetic operations

### ISSUE THREAD

**Issue by heshanpadmasiri** [ballerina-platform/nballerina#181]
@jclark for this I am planning of adding fallowing changes to the public API

1. Add new `public type BinaryNSWArithmeticOp "add"|"mul"|"sub"` (This is because not all of the current `BinaryArithmeticOp`s have a `nsw` version
2. Add new function to builder as `public function binaryNSWInt(BinaryNSWArithmeticOp op, Value lhs, Value rhs, string? name=()) returns Value` (Similar to `binaryInt` in current implementation but since not all `BinaryIntOp`s have a `nsw` version)

2 Will represent fallowing C-API functions:

- [`LLVMBuildNSWAdd`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga901f44572f6ef9f67e5f7bb496806280)
- [`LLVMBuildNSWSub`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga0ababa21464265587c66120354f857f0)
- [`LLVMBuildNSWMul`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga620c57b22a134350df2cce5e676d2b88)

I am assuming we don't need the equivalent to [`LLVMBuildNSWNeg`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#gaac84a51432d611b64b3570fc36067a48) at the moment.

**Comment by jclark** [comment]
This is for #180.

**Comment by jclark** [comment]
Hmm. That feels a bit ugly to me. We need to rethink our naming here.

Fundamentally I think there are three groups:

1. add/mul/sub
2. sdiv/srem
3. xor/or/and (and the shift operations)

where (1) has flags for wrapping. Also note that (1) corresponds to the operations that have `*.overflow` intrinsics.

The difference between (1) and (2) is that (2) is signed, whereas (1) is signless: in two's complement, (1) applied to signed and unsigned works the same.

For floats and decimals, we have only (1) and (2).

I believe the semantics we need is to include either "nuw nsw" or nothing.  The "binary" also feels a bit redundant because the only unary op is floating point negate. Also "int" in the method name feels inconsistent with "iCmp". So I suggest:

1. iArithmeticWrap(IntArithmeticOp ...) and iArithmeticNoWrap(IntArithmeticOp ...)
2. iArithmeticSigned(IntArithmeticSignedOp ...)
3. iBitwise(IntBitwiseOp ...)
