### ISSUE TITLE
Add LLVM API support for address spaces

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#188]
Needs

* pointers with address spaces,
* addrspacecast

Needed for #199

**Comment by heshanpadmasiri** [comment]
@jclark for supporting pointers with address spaces I don't think we need to add any changes to the public API because our `pointerType` function already takes an address space as an argument. We only have to handle the code generation part (already working in the `jni.llvm` side we have to fix only the `print.llvm` side)
For `addrspacecast` I am thinking of adding new function `public function addrSpaceCast(PointerValue val, PointerType desTy, string? name=()) returns PointerValue` similar to [`LLVMBuildAddrSpaceCast`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga8655643926ed8c16b1adacc916dce492) in the C API.
I wish to point out that  [`LLVMBuildAddrSpaceCast`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga8655643926ed8c16b1adacc916dce492) don't do this "cleanly" as given in the [language ref](https://llvm.org/docs/LangRef.html#addrspacecast-to-instruction). Instead it is very similar to a pointer cast in the output. For example:
```java
        LLVMTypeRef i64Type = LLVMInt64Type();
        LLVMTypeRef pointerTy1 = LLVMPointerType(i64Type, 1);
        LLVMTypeRef pointerTy2 = LLVMPointerType(i64Type, 2);
        LLVMValueRef g1 = LLVMAddGlobal(module, pointerTy1, "g1");

        LLVMTypeRef fnType = LLVMFunctionType(pointerTy2, LLVMVoidType(), 0,  0);
        LLVMValueRef testFn = LLVMAddFunction(module, "testFn", fnType);
        LLVMBasicBlockRef initBlock = LLVMAppendBasicBlock(testFn, "");
        LLVMPositionBuilderAtEnd(builder, initBlock);
        LLVMValueRef cast = LLVMBuildAddrSpaceCast(builder,g1, pointerTy2, "" );
        LLVMBuildRet(builder, cast);
``` 
in `jni` will lead to 
```
@g1 = external global i64 addrspace(1)*

define i64 addrspace(2)* @testFn() {
  ret i64 addrspace(2)* addrspacecast (i64* bitcast (i64 addrspace(1)** @g1 to i64*) to i64 addrspace(2)*)
}
```
I assume our `print.llvm` output should resemble this output

**Comment by jclark** [comment]
If we are not getting a clean addrspacecast in the LL IR, then we aren't doing it right. The example in 

https://github.com/ballerina-platform/nballerina/issues/149#issuecomment-873339983

generates

```
%2 = addrspacecast i8 addrspace(1)* %0 to i8*, !dbg !19
```

So first step is to figure out how to use the LLVM API to generate what clang generates.

**Comment by heshanpadmasiri** [comment]
If I understand this correctly above "unclean" code generation happens only when the source is a `external` pointer. It doesn't happen when it is not (works fine even if it the return value of an external function). In the case of clang even for `extern` pointers it puts an explicit load before the bit cast which fixes the issue.
For example for 
```
extern char __attribute__((address_space(1)))* g1;

long foo(char __attribute__((address_space(1))) *p1) {
    char *p0 = (char *)g1;
    return (long)p0;
}
``` 
In the IR I get
```
%2 = load i8 addrspace(1)*, i8 addrspace(1)** @g1, align 8, !dbg !19, !tbaa !20
%3 = addrspacecast i8 addrspace(1)* %2 to i8*, !dbg !24
```
With the C API (in `jni`) if I do 
```
LLVMValueRef v1 = LLVMBuildLoad(builder, g1, "");
LLVMValueRef cast = LLVMBuildAddrSpaceCast(builder,v1, pointerTy2, "test" );
```
instead of directly casting global `g1` I get the cleaner
```
  %1 = load i64 addrspace(1)*, i64 addrspace(1)** @g1, align 8
  %test = addrspacecast i64 addrspace(1)* %1 to i64*
```
So I think the problem is should the builder add a `load` before the every `addrspacecast` (Because currently it doesn't know if a pointer is global or not) or can expect there is always a load before `addrspacecast` in case that it is a `global`

**Comment by jclark** [comment]
Do all the unclean cases use `LLVMAddGlobal`?

**Comment by heshanpadmasiri** [comment]
Yes and you need to pass the global value ref directly to `addrspacecast` otherwise it is fine.

**Comment by jclark** [comment]
So the problem in that case is that the global should have an addrspace. There's an example [here](https://llvm.org/docs/LangRef.html#global-variables) :

```
@G = addrspace(5) constant float 1.0, section "foo", align 4
```

Conceptually, address space applies to the thing that is pointed to rather than the pointer itself.

I see the LLVM C API has [LLVMAddGlobalInAddressSpace](https://llvm.org/doxygen/group__LLVMCoreValueConstantGlobalVariable.html#gad8d95a7adb7424b28dc1bcb7a86b9ca6)

So we should add an optional address space parameter (with default value of 0) to our Module.addGlobal method.

**Comment by heshanpadmasiri** [comment]
It seems to work.
For example:
```
        LLVMTypeRef pointerTy2 = LLVMPointerType(i64Type, 0);
        LLVMValueRef g1 = LLVMAddGlobalInAddressSpace(module,i64Type, "g1", 3);
        ...
        LLVMValueRef cast = LLVMBuildAddrSpaceCast(builder,g1, pointerTy2, "test" );
        LLVMBuildRet(builder, cast);
```
Will lead to 
```
@g1 = external addrspace(3) global i64

define i64* @testFn() {
  ret i64* addrspacecast (i64 addrspace(3)* @g1 to i64*)
}
```
_(Only difference is it adds parenthesis)_
So I'll modify the `addGlobal` method to handle this.

**Comment by jclark** [comment]
This isn't working properly yet: getElementPtr is not dealing with address spaces at all.

**Comment by jclark** [comment]
Also need to fix up the ptrmask intrinsic: we only need it for address space 1.

**Comment by jclark** [comment]
@heshanpadmasiri I have fixed both the above problems at least enough to get the tests working. Please check my fix for getelementptr is correct in all cases and add some test cases for getelementptr with multiple address spaces. You may also need to fix the ptrmark intrinsic in the JNI impl.
