### ISSUE TITLE
Generate `dso_local` when appropriate

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#189]
clang generates function definitions using `dso_local`.

Understand what this means and do it, if it makes sense for us.

**Comment by manuranga** [comment]
This turned out to be quite the rabbit hole!
In ELF shared libraries, it is possible to replace symbols at runtime (known as "interpositions"), this can be used for debugging and other [cool link-time tricks](https://github.com/gaul/awesome-ld-preload). However this has made a lot of [people](https://www.airs.com/blog/archives/307) very [angry](https://www.facebook.com/dan.colascione/posts/10107358290728348) and has been widely regarded as a [bad move](https://www.macieira.org/blog/2012/01/sorry-state-of-dynamic-libraries-on-linux/).

Clang decided to violate ELF spec by disabling this feature unless `-fsemantic-interposition` has been passed, which feels like a sane default. But unfortunately, LLVM IR [decided](https://reviews.llvm.org/D20217#879040) to have the defaults the other way around (same as GCC).

Having `dso_local` implies symbol will not be replaced at runtime [therefore generated code can be more efficient](https://godbolt.org/z/v36xsb6YK).
But since LLVM IR has `dso_preemptable` as the default, each frontend has to deal with it separately:

* Clang emits `dso_local` for most functions, with a lot of [nuances](https://maskray.me/blog/2021-05-09-fno-semantic-interposition). 
* Rust emits `internal` linkage type for non-externs, which [implies `dso_local`](https://github.com/llvm/llvm-project/blob/d480f968ad8b56d3ee4a6b6df5532d485b0ad01e/llvm/include/llvm/IR/GlobalValue.h#L276 ), and `hidden` visibility style for [build in](https://github.com/rust-lang/rust/blob/6f9df55a782c5373c75dfa23e6ba50f8b42318ef/compiler/rustc_codegen_llvm/src/mono_item.rs#L72) functions which also imply `dso_local`.
* Swift emits `internal` linkage type for non-public functions, and emits `hidden` for wrapper functions.

Conclusion: 
Since we are not doing shared libraries currently, `dso_local` doesn't matter much. We should implement the `internal` linkage type for private symbols.

Ones we have multiple modules, revisit and verify that we don't have any `GOT` or `PLT` in the resulting assembly.

Additionally, I found `linkonce` interesting, might be useful in pre-written ll that we plan to link to everything.

**Comment by jclark** [comment]
Sounds like it would be slightly better to generate `dso_local` for public functions, so that we can compile with `-fpic` if we want to without a performance hit. But as far as I can see there's no way in the C API to do this (@heshanpadmasiri please check this). So I think the conclusion is to do nothing...

I wonder whether interposition would be useful for some of the observability stuff Choreo is doing.

We are using `internal` for non-public module symbols already. Also I have already implemented the `.ll` that gets linked into everything (but generated from C). My understanding is we want `linkonce_odr` not `linkonce` so as to allow inlining, and that's what I'm using: https://github.com/ballerina-platform/nballerina/blob/29548603a10ce0539e77dd26bdd8dd211657a036/runtime/Makefile#L25

I don't completely understand the point of `hidden`.
