### ISSUE TITLE
Expand nback.llvm to support int operations

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#20]
Add llvm constructs needed to support integer operations.

Ref:
https://github.com/ruvi-d/nballerina-tests/tree/master/stage_1

**Comment by jclark** [comment]
Can we separate this issue into specific instructions/features?

We need at least:

- structure types - enough to do {i64, i1}
- ability to call intrinsics
- icmp

Before implementing, I would like to see the API addition in the issue.

**Comment by heshanpadmasiri** [comment]
I think these are the things we need for this issue:

LLVM instructions:
- `extractvalue` (get values from the structure types) [`LLVMBuildExtractValue`]
- `br` (we need both conditional and unconditional variants) [`LLVMBuildBr`, `LLVMBuildCondBr`]
- `icmp` (strictly speaking we may not need all the possible predicates but I think we can support all similar to how we do `binaryInt`) [`LLVMBuildICmp`]
- `unreachable` (I think this is optional but better if we can add this after calling abort and should be trivial to implement)[`LLVMBuildUnreachable`]

Type support:
- structure types [`llvm::StructType`] (I don't  think we need all the features just ability to define a type using element types and being able to get the type of a given (by index) element)

Other modifications:
- We need to support external functions (such as `llvm.sadd.with.overflow`)

**Comment by heshanpadmasiri** [comment]
> Can we separate this issue into specific instructions/features?
> 
> We need at least:
> 
> * structure types - enough to do {i64, i1}
> * ability to call intrinsics
> * icmp
> 
> Before implementing, I would like to see the API addition in the issue.

I was thinking of making the first PR to deal with the structure types and external function( I think this only need small changes to the current function implementation. But It may make sense to break it in to a separate issue because it is unrelated to structures)
- Way to define structure types and use them as a type of a value / return type of function
- `extractvalue` so we can get values out of them by index

Then do a separate pr to handle branching and comparisons (`br` and `icmp`). Would it be okay if we break this in to two issues like that

**Comment by manuranga** [comment]
Closed in favor of #24  #25
