### ISSUE TITLE
Extend nback.llvm to support function attributes

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#21]
C API has

* LLVMAttributeIndex (what the attribute applies to: function, return value or specific parameter)
* LLVMAddAttributeAtIndex 
* LLVMCreateStringAttribute
* LLVMCreateEnumAttribute (looks like `val` argument is typically 0), which needs
   * LLVMGetEnumAttributeKindForName

**Comment by jclark** [comment]
We need only EnumAttributes without an argument for now (things like `noreturn`, `cold`).

**Comment by jclark** [comment]
@heshanpadmasiri Could you propose in this issue an extension to the nback.llvm API to handle this?

**Comment by heshanpadmasiri** [comment]
Since we are purely concerned about adding attributes to functions and they are not going to have arguments I think the minimum we need to implement is this

1. In our `Function` implementation add the equivalent of `addAttribute` (ref: https://llvm.org/doxygen/classllvm_1_1Function.html#ae8ef440a4592cd8b97ddf1826d22d9f9).
2. I think for our use case we can use a simple list of `Attributes` in each function where we add the new attribute if it is not in it already. So currently I don't think we necessarily need to support the index value
3. Since we are not allowing user to create define their own attributes or add arguments at the moment I think we can use a simple type similar to `BinaryArithmeticOp` for `Attribute`. (We can extend this down the line when we support these features giving the user methods to construct the)

So the only addition to the API will be `addAttribute` for our `Function` and public type `Attribute`

**Comment by jclark** [comment]
Let's keep to the C API as the reference.

LLVM has enum attributes and string attributes. What you suggest is combining LLVMAddAttributeAtIndex and LLVMCreateEnumAttribute.  The index value is saying what the attribute attaches to, which is either the function itself, the return value or a parameter.

So I would suggest a slight variation:

```
type EnumAttribute "noreturn"|"cold"; // add as needed

// on Function
public function addEnumAttribute(EnumAttribute attr);
```

The index would implicitly be LLVMAttributeFunctionIndex i.e. applies to function; we can add an explicit argument for that later if we need it.
