### ISSUE TITLE
Vstring13 is not getting optimized as well as it should

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#264]
The assembly output for the Vstring13 shows LLVM is nearly but not quite optimizing as one would hope.
[Vstring13.s.txt](https://github.com/ballerina-platform/nballerina/files/6875945/Vstring13.s.txt)

The source has 6 calls to isKeyword, which is somehow being optimized to 4 calls.

It is failing to detect that it is impossible for _bal_string_heap_eq to be called: the IMMEDIATE_FLAG is set on one of the arguments, which means that taggedStringEqual can never call _bal_string_heap_eq.

The fix might be to change the optimization pipeline #265

**Comment by KavinduZoysa** [comment]
> The source has 6 calls to isKeyword, which is somehow being optimized to 4 calls.
> 

Basically this optimization happens when it inlines the _B_isKeyword method to _B_main method. These are my observations.

1. If we run this command, `llvm-link-11 -o Vstring13_linked.bc Vstring13.ll ../runtime/balrt_inline.bc && clang-11 -S -O2 Vstring13_linked.bc -Rpass=inline -o Vstring13.s`, we can get the below output. This command reports transformations for inline pass. 

```
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _bal_string_eq inlined into _B_isKeyword with (cost=30, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _B_isKeyword inlined into _B_main with (cost=190, threshold=225) [-Rpass=inline]
remark: <unknown>:0:0: _B_isKeyword inlined into _B_main with (cost=20, threshold=225) [-Rpass=inline]
```
     
   Last 2 entries represent the inlining of first and last _B_isKeyword  method call.

2. If we run this command, `llvm-link-11 -o Vstring13_linked.bc Vstring13.ll runtime/balrt_inline.bc && clang-11 -S -O2 -mllvm -opt-bisect-limit=91 Vstring13_linked.bc -o Vstring13.s`, we can see at 91st pass (**Function Integration/Inlining on SCC (_B_main)**) is responsible for this optimization. 

```
BISECT: running pass (90) Remove unused exception handling info on SCC (_B_main)
BISECT: running pass (91) Function Integration/Inlining on SCC (_B_main)
BISECT: NOT running pass (92) Deduce function attributes on SCC (_B_main)
```

3. Also we can replicate this optimization using opt-11 by following below steps.

- Link the balrt_inline.bc and get the IR. `llvm-link-11 -o Vstring13_linked.bc Vstring13.ll runtime/balrt_inline.bc && llvm-dis-11 Vstring13_linked.bc -o Vstring13_linked.ll`
- Mark _B_isKeyword and _bal_string_eq as `alwaysinline`
- Run `opt-11 -S -mem2reg -inline -instsimplify Vstring13_linked.ll -o inline.ll`
If we check the first `_Bio__println` call, related block looks like below. 

```
_B_isKeyword.exit:                                ; preds = %31, %30, %24, %18
  call void @_Bio__println(i8 addrspace(1)* getelementptr (i8, i8 addrspace(1)* null, i64 72057594037927937))
```

Based on above observations we can say that this optimization happens because it inlines _B_isKeyword to _B_main. AFAIU we have to figure out why this inlining happens. I am working on that. @jclark i really appreciate your input on this.

**Comment by manuranga** [comment]
@KavinduZoysa the key thing to find out is not why they are getting optimized, but why others are not.

**Comment by jclark** [comment]
We need it to be able to optimize when isKeyword is not inlined: knowing one of the arguments to taggedStringEqual is immediate should be sufficient to allow it to remove the call to _bal_string_heap_eq.  But it seems it can only do this when both arguments to taggedStringEqual are immediate. Why?

**Comment by jclark** [comment]
Getting it to inline isKeyword would not solve the problem. The issue is getting it to optimize taggedStringEqual and so _bal_string_eq, when only one argument has a value known at compile time.

**Comment by jclark** [comment]
In today's call, @KavinduZoysa said he thinks the problem relates to addrspacecast.

That then raises the question of whether this is something that can be improved in LLVM or is it inherent in the semantics of multiple address spaces.

(BTW, I also noticed that `llvm-link` seems to be removing the non-integral address space part of the data layout, but that this doesn't happen with -S.)

**Comment by KavinduZoysa** [comment]
> In today's call, @KavinduZoysa said he thinks the problem relates to addrspacecast.
> 

To verify this, I have written below sample code by removing the addrspacecast in _bal_string_eq method.

```
define dso_local zeroext i1 @_bal_string_eq(i8 addrspace(1)* %0, i8 addrspace(1)* %1) {
  %3 = icmp eq i8 addrspace(1)* %0, %1
  br i1 %3, label %12, label %4

4:                                                ; preds = %2
  %5 = ptrtoint i8 addrspace(1)* %1 to i64
  %6 = ptrtoint i8 addrspace(1)* %0 to i64
  %7 = or i64 %5, %6
  %8 = and i64 %7, 2305843009213693952
  %9 = icmp eq i64 %8, 0
  br i1 %9, label %10, label %12

10:                                               ; preds = %4
  %11 = tail call zeroext i1 @_bal_string_heap_eq(i8 addrspace(1)* %0, i8 addrspace(1)* %1) 
  br label %12

12:                                               ; preds = %10, %4, %2
  %13 = phi i1 [ %11, %10 ], [ true, %2 ], [ false, %4 ]
  ret i1 %13
}

define i1 @_B_main(i8 addrspace(1)* %0) {
    %_1 = call i1 @_bal_string_eq(i8 addrspace(1)* getelementptr (i8, i8 addrspace(1)* null, i64 3098316506530080114), i8 addrspace(1)* %0)
}

declare dso_local zeroext i1 @_bal_string_heap_eq(i8 addrspace(1)*, i8 addrspace(1)*) local_unnamed_addr
```
If we run the `opt-11 -instcombine -inline -debug-pass=Arguments -S test.ll`, we can see the _bal_string_eq is inlined and _bal_string_heap_eq is removed. The inline pass alone does not remove the _bal_string_heap_eq, we have to use instcombine before or after inline.

With addrspacecast we cannot see such an optimization. AFAIU the reason is like this.

When addrspacecast is available : The inscombine pass change the getelementptr to inttoptr, and when inlining, there is a series of casts available at ptrtoint(ptrtoint -> addrspacecast -> inttoptr). Inside the inline pass, it calls the instcombine pass. When ptrtoint instruction is visiting as shown [here](https://github.com/llvm/llvm-project/blob/43ff75f2c3feef64f9d73328230d34dac8832a91/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L1928) and if we go through that method we can see that ptrtoint -> addrspacecast is [disallowed](https://github.com/llvm/llvm-project/blob/43ff75f2c3feef64f9d73328230d34dac8832a91/llvm/lib/IR/Instructions.cpp#L2690).

> That then raises the question of whether this is something that can be improved in LLVM or is it inherent in the semantics of multiple address spaces.
> 

Yes, I will try to find whether this needs to be handled in LLVM or not. But I think it is okay to disallow optimize ptrtoint when the value comes from different AS.

If we handle this in our side and if we keep the pointers of _bal_string_eq in AS 1, we have to face problem that it is not allowed to perform ptrtoint for pointers which are located in non-integral AS(ni:1). So I suggest to move pointers to AS 0, because we do not need to triger GC in this method (also in _bal_string_heap_eq). So before we call this method we have to do addrspacecast in our generated IR. I will keep on testing this.

**Comment by jclark** [comment]
If we do addrspacecast to address space 0 in our IR, before calling _bal_string_eq, won't that have the same problem?

I am guessing our code needs not to do the addrspacecast to address space 1 for constant strings.

**Comment by manuranga** [comment]
It's wired that
> The inscombine pass change the getelementptr to inttoptr

Could it be that, we are seeing cast in `taggedPtrBits` getting inlined and `getelementptr` disappearing altogether?

**Comment by KavinduZoysa** [comment]
> 
> Could it be that, we are seeing cast in `taggedPtrBits` getting inlined and `getelementptr` disappearing altogether?

This change happens before the inline, if we run only the -instcombine, the getelementptr instruction changes to inttoptr.

**Comment by KavinduZoysa** [comment]
@jclark The reason to optimize when both values are known is like this. 
This optimzation happens only when both pointer values are same. The first icmp instruction of _bal_string_eq checks whether both pointers are same. Since both values are same, other basic blocks will not be executed. 

In **gollvm**, they have added a pass to remove addrspacecast for globals which are initialized. As they mentioned, this pass is added to support pointer to integer cast available in non integral AS (Please find more information in https://go-review.googlesource.com/c/gollvm/+/152001). Also **Julia** has written a pass to remove `ni` part from data layout. I am not sure whether the writing pass is the correct approach for our case, but as I understood gollvm and julia has written these passes to element issues in non integral AS.

**Comment by jclark** [comment]
#276 fixes this (as much as we can).

**Comment by KavinduZoysa** [comment]
@jclark, shall we create a new issue to track, writing a pass to remove addrspacecast? (gollvm and Juila have this pass). In the future we will also need such a pass. Please check https://github.com/ballerina-platform/nballerina/issues/264#issuecomment-892044937
