### ISSUE TITLE
Implement specialized representations for `int[]` and `float[]`

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#329]
This improves the initial implementation of arrays from #328 to provide specialized implementations for `int[]` and `float[]`.

This should use the idea in #204.

After this we can tackle #169

**Comment by jclark** [comment]
To implement #204, we need to identify all cases where there can an implicit widening to a list value. In subset 7, the BIR insns that can do this are:

- ListGet
- MappingGet
- Call (for both arguments and return)
- Assign
- Ret

The insns that can restore an exact bit are
- CondNarrow
- TypeCast

**Comment by jclark** [comment]
~~To keep things simple to start with, we could have the array object in the generic case include the bit vector of member types as well as a pointer to a descriptor. This means would can need only three descriptors (int, float and generic) and so we could put them in the runtime.~~

We now have the init.bal machinery to do this properly.

**Comment by jclark** [comment]
Prerequisites are #582 and then #583.

**Comment by manuranga** [comment]
Currently all arrays are tagged pointer arrays, but after this `int[]` and `float[]` will store untagged representations. Interplay with this and exactness creates following cases. 

| Comparison                       | Current behavior                             |  Proposed behavior                                                               |
|----------------------------------|----------------------------------------------|----------------------------------------------------------------------------------|
| Exact int[] vs exact int[]       | `_bal_array_int_compare` - Untag and compare | `_bal_array_exact_int_compare` - Direct access and compare                       |
| Exact int[] vs inexact int[]     | Not possible                                 | `_bal_array_int_compare` - Retrieve via `get` pointer in desc, untag and compare |
| Inexact int[] vs inexact int[]   | Not possible                                 | "                                                                                |
| Exact int?[] vs Exact int?[]     | `_bal_array_int_compare` - Untag and compare | "                                                                                |
| Exact int?[] vs inexact int?[]   | `_bal_array_int_compare` - Untag and compare | "                                                                                |
| Inexact int?[] vs inexact int?[] | `_bal_array_int_compare` -Untag and compare  | "                                                                                |

For simplicity, I don't think we should provide specialized implementations for each. We'll have two C functions `_bal_array_exact_int_compare` and `_bal_array_int_compare`. We may also consider `_bal_array_exact_byte_compare` in the future. No need to store these in the typedesc. In preparation for this, we should make `_bal_array_int_compare` retrieve values via `get` function pointer in #583

**Comment by jclark** [comment]
I would just do the first one (the exact case). In the second case, the overhead of retrieval via function pointer access (and knock-on effects from preventing inlining) is going to mean that gains from a specialized implementation are minimal.

**Comment by manuranga** [comment]
I need to change `push` and `print` as well. With `push` we have following options.

1) Go through`set` function ptr, panic if PanicCode != 0
2) Have push operation as a pointer in typedesc as well
3) Look at bitset and pick what to do

I am going ahead with 1

**Comment by jclark** [comment]
1 is good: push should panic directly because it's a function not an insn.

We should have an exact implementation of push also, though we can add that later.

**Comment by manuranga** [comment]
Progress update: I added exact int array set (via c function) and get (via code gen). Get side is working fine and LLVM is able to hoist the exactness checking out of the loop. Set side it not getting inlined, not sure why, I added `alwaysinline` the same way we add `linkonce_odr`, still didn't work. Anyway as we discussed, this is not the correct way to do exact set, I only did this get everything to a working state.

I am planing to pick `is_exact && index < length` as the fast path and let others go though the function pointer. But I don't think LLVM can hoist it because it might not be aware when the `length` can/can't be updated. I need see if LLVM's [DependenceAnalysis](https://llvm.org/doxygen/DependenceAnalysis_8cpp_source.html) can figure it out, perhaps `noalias` can help.

**Comment by jclark** [comment]
It's not the end of the world if it can't hoist: branches should be highly predictable.

**Comment by manuranga** [comment]
Progress update: Set in a loop produce following loop body for the exact path:

```ballerina
function initArr(int[] arr) {
    foreach int i in 0 ..< arr.length() {
        arr[i] = i;
    }
}
```
```
100000BF0: 49 8B 44 24 18             movq   0x18(%r12), %rax
100000BF5: 48 89 1C D8                movq   %rbx, (%rax,%rbx,8)
100000BF9: 48 FF C3                   incq   %rbx
100000BFC: 49 39 DF                   cmpq   %rbx, %r15              // %r15 contains the length of the array
100000BFF: 74 C7                      je     0x100000bc8  ; <+232>
100000C01: 49 3B 5C 24 08             cmpq   0x8(%r12), %rbx         //  %r12 is list ptr,  0x8(%r12) is also array length
100000C06: 72 E8                      jb     0x100000bf0  ; <+272>
```
Exactness check is hosted, which is good. But ideally it should have a single `cmpq`, two`cmpq`s above are redundant. Since in [C mock-up](https://godbolt.org/z/eaGjeGb1s) there is only a single jump, it should be possible to improve this.

I perf tested the merge sort (replaced any[] with int[]) but no statistically significant improvement. Possibly because we are mainly using push. Should create an issue for this.

Incrementing each element in a int list had around 10% improvement even with the above mentioned extra jump.
```
/Users/manu/checkout/nballerina/test ❮❮❮ hyperfine -i --warmup 3 "./arr-incriment.exe" "./arr-incriment.specialize.exe"
Benchmark #1: ./arr-incriment.exe
  Time (mean ± σ):      2.949 s ±  0.045 s    [User: 2.063 s, System: 0.878 s]
  Range (min … max):    2.889 s …  3.028 s    10 runs
 
Benchmark #2: ./arr-incriment.specialize.exe
  Time (mean ± σ):      2.649 s ±  0.024 s    [User: 1.762 s, System: 0.883 s]
  Range (min … max):    2.611 s …  2.693 s    10 runs
 
Summary
  './arr-incriment.specialize.exe' ran
    1.11 ± 0.02 times faster than './arr-incriment.exe'
```

I plan to generalize this to float, do some clean up and send the PR. I can look at the redundant branch afterwards.

**Comment by jclark** [comment]
There's an `int[]` version of merge sort in 07-bench.

What exactly is your benchmark comparing? As you say, merge sort mostly uses `push`, so we need to fix that to get something meaningful.  A quicksort would probably be a better comparison for this.  I would also expect `float[]` to give more of an improvement, since it avoids boxing (whereas `int` will mostly use immediate ints).

**Comment by manuranga** [comment]
Currently the list desc has `TaggedPtr (*get)(TaggedPtr lp, int64_t index)` and `PanicCode (*set)(TaggedPtr lp, int64_t index, TaggedPtr val)`. I am in the process of adding `getInt`, `getFloat`, `setInt` and `setFloat` to avoid extra tagging/untagging as we discussed.

But since `getFloat` (and `getInt`) should be able to panic, it's has to return `{ PanicCode, double}` or `{ boolean, double }`.
