### ISSUE TITLE
Add minimal LLVM module support for debug information

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#381]
In order to get backtraces with line numbers #6, we need to generate some minimal debug information #7.

This will need some functionality from LLVMDIBuilder.

**Comment by jclark** [comment]
@heshanpadmasiri Can you figure out what is the minimum API we need in order to be able to generate what is described here https://github.com/ballerina-platform/nballerina/issues/46#issuecomment-884259636

**Comment by heshanpadmasiri** [comment]
We will need to support [`LLVMDIBuilderRef`](https://llvm.org/doxygen/group__LLVMCSupportTypes.html#gae7276221889549b4cf3b3f2297a8333e) and [`LLVMMetadataRef`](https://llvm.org/doxygen/group__LLVMCSupportTypes.html#gab9f52d9777af781812e7bffdd491d01e) objects. I think we can do the `LLVMDIBuilderRef` similar to how we handle `LLVMBuilderRef` (-> `llvm:Builder`) and `LLVMMetadataRef` similar to how we handle `LLVMValueRef` (-> `llvm:Value`).

We need fallowing functions to support the given debug ir

- [`LLVMDIBuilderCreateCompileUnit`](https://llvm.org/doxygen/DebugInfo_8cpp.html#ac80c97dafb7ed1815c40df3e29ac574d)  for 
```
!llvm.dbg.cu = !{!0}
!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, emissionKind: FullDebug)
```
- [`LLVMAddModuleFlag`](https://llvm.org/doxygen/group__LLVMCCoreModule.html#ga91746975955737845b0f9a3b33c415f5) and [`LLVMValueAsMetadata`](https://llvm.org/doxygen/group__LLVMCCoreValueMetadata.html#gaa97820d45655d6345b92c0ac334d8b25) (for `i32 3 part`) for
```
!llvm.module.flags = !{!5}
!5 = !{i32 2, !"Debug Info Version", i32 3}
```
- [`LLVMDIBuilderCreateFile`](https://llvm.org/doxygen/DebugInfo_8cpp.html#aee236259f740de70edbb17b7a274aa3f) for
```
!1 = !DIFile(filename: "Plist00.bal", directory: "PATH_TO_BAL_SOURCE")
```
- [`LLVMDIBuilderCreateFunction`](https://llvm.org/doxygen/DebugInfo_8cpp.html#a16e177b130697369b80b40e2a6e4b4bd) for
```
!2 = distinct !DISubprogram(name: "_B_main", scope: !1, file: !1, line: 1, type: !3, unit: !0)
```
- [`LLVMDIBuilderCreateSubroutineType`](https://llvm.org/doxygen/DebugInfo_8cpp.html#a96266a67a61ce67e77498296bbae2551) for
```
!3 = !DISubroutineType(types: !{null})
```
_I am not sure if this is enough because passing null to this result in fallowing code (note it is not explicitly saying null). If this is not working we may have figure out how to make this null explicitly_
```
!4 = !DISubroutineType(types: !5)
!5 = !{}
```
- [`LLVMSetSubprogram`](https://llvm.org/doxygen/DebugInfo_8cpp.html#a3fb4cb7331aa97b2bdd91044b5c33fad) to set the debug flag at function declaration
```
define void @_B_main() !dbg !2 {
```
- [`LLVMSetCurrentDebugLocation2`](https://llvm.org/doxygen/group__LLVMCCoreInstructionBuilder.html#ga3106d877cfdc8bc73fc460ad70c69bd6) for setting debug info at function call
```
call void @_bal_panic(i64 %13), !dbg !4
```
_This is done by first setting the debug info before instruction building and then setting it to null after instruction building. We can also add an explicit function to reset instead of setting to null_
```
        LLVMSetCurrentDebugLocation2(builder, callMetadata);
        LLVMBuildCall(builder, testFn, arg, 0, "");
        LLVMSetCurrentDebugLocation2(builder, null);
```
- [`LLVMDIBuilderCreateDebugLocation`](https://llvm.org/doxygen/DebugInfo_8cpp.html#a297455fb958aa499228de05966751977) for setting
```
!4 = !DILocation(line: 5, column: 16, scope: !2)
```

**Comment by jclark** [comment]
Overall that seems fine. Some specific comments:
- for LLVMDIBuilderCreateCompileUnit, let's use an included record parameter with just the fields we need for now (default others to something sensible)
- omit the "2" from LVMSetCurrentDebugLocation2; stick to nil for clearing the debug info
- for LLVMDIBuilderCreateSubroutineType, can our API just omit the parameter types and flags for now? Maybe you can use a zero-length array
- can we do AddModuleFlag in a more strongly typed way? e.g. `type ModuleFlag ["Debug Info Version", int] | (whatever else we need)`
