### ISSUE TITLE
Organize test suite into directories

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#419]
Organize test suite into directories.

Alternative to #358

**Comment by manuranga** [comment]
Current proposal is to use a format like:
`testSuite/01-int/subtract-01-v.bal`

**Comment by jclark** [comment]
Just: `testSuite/01-int/subtract1-v.bal`

The number in the filename is not required.

**Comment by manuranga** [comment]
Proposed renamings https://gist.github.com/manuranga/97f3bdcaad2e31cf6c6f9d0bc4a79fdb

This is purely based on the original names, not on labels.

**Comment by jclark** [comment]
There are a couple like this:

> Vnileq03             -> 03-nil/equal4-v.bal

I think you should start at 1 in each created directory rather than adding 1.

So 06-const/19-e.bal  would be 1-e.bal.

In 03. I would distinguish langlib and lib.

I would merge 01-const into 01-int.

I would merge 07-panic into 07-error.

Does it make sense to categorize F cases by subset? Maybe just put all F cases into a fail directory.

There's lots more that could be tweaked, but I think it's easier just to do it and then tweak later.
