### ISSUE TITLE
Add an expect method for `VariableLengthToken`s to Tokenizer

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#474]
Currently there is an `expect` method for fixed tokens. Adding similar method for `VariableLengthToken` will

- Simplify usage code by removing one level of indentation
- Improve the parser error messages

**Comment by manuranga** [comment]
I propose a method like 
```ballerina
function expectOfCode(VariableTokenCode code, string? customMsg = ()) returns string|err:Syntax
```
Which will give error message like 

`'expected 'identifier'; got ';' {....}`

**Comment by jclark** [comment]
Why does it need to be a separate method? Just add `|VariableLengthTokenCode` to the parameter type.

If we're going to give some love to the expect method, we should fix it up to be able to say that one of several tokens is expected.

Edited: Answering my own question: so you can get the string

**Comment by jclark** [comment]
I would want the message to say: `expected an identifier; got ':'` (without quoting `identifier`).

I don't like the proposed function name.

What tokens is this really going to be useful for? It's not going to work for numbers. Do you have cases in mind other than identifiers? If not, I would just do `expectIdentifier`.

I'm not sure about customMsg.  What is the specific place you are planning to use this? I would expect you would want to only customize part of the message (or perhaps extend it) rather than replacing the entire message. Maybe it could replace "an identifier" in the message, although this sort of thing is bad for error message localization.

**Comment by manuranga** [comment]
`expectIdentifier` makes more sense. Added a `customMsg` to preserve existing error messages, but they don't provide a lot of value, will get rid of it.
