### ISSUE TITLE
Subset-08 grammer should document allowing`"(" ")"` in `type-desc`

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#505]
Allowed in the implementation, since `?` is already allowed doesn't make sense to disallow `()`

**Comment by jclark** [comment]
I clarified what the grammar is trying to achieve in https://github.com/ballerina-platform/nballerina/commit/750e07049a81651860c272349e39b8a9581ea6b3

It allows parentheses in array-member-type-desc. If we allowed it in other places, it would either make the grammar unnecessarily complicated or allow types that we do not yet support. If you think otherwise, please propose a specific change to the grammar.
