### ISSUE TITLE
Implement SemType projection

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#522]
Projection is a an operation on types Proj(T, K) where T is a subtype of list or a subtype of mapping, and K is a subtype of int or string respectively, such that if v belongs to T and k belongs to K, then `v[k]` belongs to Proj(T,K). The spec calls Proj(T,K) [the member type of K in T](https://ballerina.io/spec/lang/2021R1/#section_5.4).

**Comment by jclark** [comment]
This is discussed in section 4.4.1 of the [Castagna](https://arxiv.org/abs/1809.01427) paper.

**Comment by jclark** [comment]
We need to do a bit of this in order to solve #518.

**Comment by jclark** [comment]
The BDD is a disjunction of conjunctions of possibly negated atoms.  So a first approximation is:

- project each positive atom independently
- ignore each negated atom
- combine the projections in the same way as the corresponding atoms

The question is whether we can get something more precise by paying attention to negated atoms. We cannot simply project and combine. For example the projection of `(int|string)[] & !(string[])` is not `int`, since `!(string[])` means it is not the case that every member is a string, rather than every member is a string.

**Comment by jclark** [comment]
Consider:

```
[int?, int?] & ![(), ()] & ![int, ()] & ![(), int]
```

This is (I think) equivalent to `[int, int]`, so the projection is always `int` regardless of the key type.

**Comment by jclark** [comment]
I am stuck on equation 4.17 on page 15:38 of the [Castagna](https://arxiv.org/abs/1809.01427) paper. He gives this formula (w/o the red lines, of course) for the type of e[0]

![ProjectionQuestion](https://user-images.githubusercontent.com/499966/135749552-e70cdea8-faca-4d47-9df2-9a543030cacf.png)

This is when e has type:

![ProjectionEquation](https://user-images.githubusercontent.com/499966/135749972-7b428574-50ea-4327-80de-f4df54ed69b7.png)

But it seems to me that since one of the possibilities for N' is the empty set, this is equivalent to the much simpler form without the parts in red that have been crossed out. So I think there is something basic that I am not understanding properly.

**Comment by jclark** [comment]
Consider the very simple case where the type of e is (in Ballerina syntax with the addition of `!` for not):

```
[S1, T1] & ![S2, T2]
```

In this case I is {1}, P1 is {1}, N1 is {2}. So the possibilities for N' are {} and {2}. Thus the formula 4.17 reduces to:

```
S1 | (S1 & !S2)
```

But that is just S1.

**Comment by jclark** [comment]
@rdhananjaya @manuranga Any thoughts?

**Comment by manuranga** [comment]
After staring at this section for almost 5 hours, I think I understand it.

You are correct, it'll give `S1`, but as it says this is just an approximation, by that it seems to mean an upper bound.
4.20 gives the accurate answer:
```
([S1, T1] & ![S2, T2])[0] = S1 & !S2   if T1 <: T2
                            S1         else
```
(note: `<:` stands for subtype, not proper subtype)

**Comment by manuranga** [comment]
Interesting test case:
```
type Light "RED"|"YELLOW"|"GREEN";
type State "ON"|"OFF";
type TrafficReading [Light, State];
type MaybeGo ["RED", "OFF"] | ["YELLOW", "OFF"];
type DefinitelyGo ["GREEN", "ON"] | ["YELLOW", "ON"];
type DefinitelyStop TrafficReading & !MaybeGo & !DefinitelyGo;

// @type DefinitelyStop[0] = "RED" | "GREEN"
```

**Comment by jclark** [comment]
You're ahead of me: I haven't yet tried to understand 4.20 (i.e. bottom half of page 15:38), but your example makes sense. Does 4.20 handle my example in  https://github.com/ballerina-platform/nballerina/issues/522#issuecomment-932866001? I don't think it does. I suspect 4.20 is also an approximation: just a more precise one than 4.17.

For our purposes, I think we can only get negated atoms when we have readonly types (since for mutable types we use the "read-only difference" operation) or if we add a `!` type operator.  So for subset 9 and fixing #518 we can implement the simplification with the red lines. When we implement singleton types, we will then need to extend this to deal with the key being an string subtype rather than a constant string (and similarly for lists).

**Comment by manuranga** [comment]
> Does 4.20 handle my example

I don't think so.

> I suspect 4.20 is also an approximation

Yes, I thought so as well. That is why I wrote the above example. I didn't notice that your example already illustrates this.

But I could be wrong, because it's not entirely clear to me how to pick the correct `N'`.

Eg: In your example, one could pick `N'` such that `Sn` is `int?` and `never`, and that will give the correct answer. On the other hand, if one picks `N'` such that `Sn` is `int` and `()` it will give the wrong answer.


So maybe when it comes to subtyping algoritam, it will always be correct, since it will try all the combinations.

**Comment by jclark** [comment]
> But I could be wrong, because it's not entirely clear to me how to pick the correct `N'`.

You have to take the union for every N' that satisfies the criteria. So to handle my example right, all the Sn would have to include `()`.

Implementing requires transforming the BDD to turn `[S1,S2]&![T1,T2]` into `[S1&!T1,S2]|[S1,S2&!T2]`, which is going to blow with large records if done naively. I think we can manage without this for quite a while.

**Comment by jclark** [comment]
This is also covered in Andrew Kent's [tutorial](https://pnwamk.github.io/sst-tutorial/#%28part._.Product_.Projection%29).

**Comment by manuranga** [comment]
I found it easier to imagine SemType product as a Cartesian product.
<img src="https://user-images.githubusercontent.com/1686124/135827206-34056fdd-2bb5-4dae-bd3c-e9fad773338d.jpg" width="250" height="250">

Then you can see union with a negation (in other words subtraction) will look as below. You'd simply have to cut out one square from another square. Lets take `e = (S₁, T₁) & !(S₂, T₂)`


<img src="https://user-images.githubusercontent.com/1686124/135896079-a64b015f-4e7f-44f3-a8a8-6c616855751c.jpg" width="400" height="250">


Now the projection becomes quite literally the projection onto the axis, i.e. `e[0]` is the shadow cast by this shape on the horizontal axis.

#### How paper derives the approximation

We can see resulting shape can be alternatively expressed as below:

<img src="https://user-images.githubusercontent.com/1686124/135828204-7e42d44d-0f91-4208-8f36-a79fd1ba274b.jpg" width="700" height="200">

Now we can see : `(S₁, T₁) & !(S₂, T₂) = (S₁ & !S₂, T₁) | (S₁, T₁ & !T₂)`

Thinking shadow casted by sum, is the sum of shadows casted by each part, one can assume, it's possible to trivially sum up first the parts to get the projection, ie: `(S₁ & !S₂) | S₁`. This is what paper refers to as an approximation in 4.17.
But this incorrect since parts with zero height casts no shadows.

#### Precise answer

To get the precise answer, sum up first of each term when second part is non-zero (≠ ∅). Then you'll get the equation analogues to 4.20 in the paper. (note that you can write `T₁ & !T₂ ≠ ∅` as `T₁ ≮: T₂`)

#### Generalizing

This trivially generalizes to higher dimensions, (i.e. n-tuples), since it's just higher dimensional Cartesian spaces. But it does not trivially generalize to multiple terms. This is because `(e₁ - e₂ - e₃)[0]  ≠ ((e₁ - e₂)[0] - e₃)[0]`.

continue on the next comment ...

**Comment by jclark** [comment]
We have done enough of this, I believe, to keep us going till #575

**Comment by jclark** [comment]
Remaining part is #845, so closing this.
