### ISSUE TITLE
Make the build pass with debug information enabled for the runtime

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/nballerina#636]
Build should pass successfully with  `make CFLAGS="-g" test`.

Currently it breaks in two places
1. There is a test failure in runtime, at `compareBacktrace`
2. LLVM linking fails with `linking module flags 'Debug Info Version': IDs have conflicting behaviors`

**Comment by KavinduZoysa** [comment]
This is the reason for runtime test failure.

`CFLAGS="-g"` overrides the -O2 and now backtrace has more trace lines than the previous one. 
Printing these trace lines is controlled by the parameter `start` as shown below.
https://github.com/ballerina-platform/nballerina/blob/64b296e57ffe1078106fc4f38109507aeaa87f73/runtime/error.c#L143

Since we have more trace lines, the assertion fails in the test.
But if we use `CFLAGS="-g -O2"` runtime tests pass.

**Comment by jclark** [comment]
Can we make the test work even when -O2 is not specified?

**Comment by KavinduZoysa** [comment]
Yes, we change the value of `start` parameter to skip unnecessary trace lines.

**Comment by KavinduZoysa** [comment]
The reason for the 2nd error is,

The behaviour flag for `"Debug Info Version"` is different. With the -g flag, it creates behaviour flag 2 (warning) and our compiler produces behaviour flag 1(error). As mentioned [here](https://releases.llvm.org/12.0.0/docs/LangRef.html#module-flags-metadata), when linking, the same flag ID cannot have multiple behaviours except Require and Override behaviours.

**Comment by jclark** [comment]
OK, I understand now.

**Comment by KavinduZoysa** [comment]
@jclark, can we close this issue?

**Comment by jclark** [comment]
Have we fixed point 1?

**Comment by KavinduZoysa** [comment]
@jclark, as explained in https://github.com/ballerina-platform/nballerina/issues/636#issuecomment-952707688, the reason for this failure is non-optimized code has more trace lines than expected. 
Do we need to change the test to pass for both cases (-g -O2 and -O2)?

**Comment by jclark** [comment]
Yes.

**Comment by jclark** [comment]
On Ubuntu 21.10, `make test` in runtime fails with segfaults in error_backtrace1 and failure in error_backtrace2.

The code is broken: cmpTrace is not being passed the length of the expectedTrace array, so it can access memory past the end of the array if the traces don't match.

We need a more robust testing strategy.

**Comment by jclark** [comment]
valgrind output
```
Invalid read of size 1
==840756==    at 0x4849C56: strlen (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==840756==    by 0x4025A2: cmpTrace (test_utils.h:63)
==840756==    by 0x402849: genAndCmpTrace (error_backtrace1.c:31)
==840756==    by 0x402B2C: func1 (error_backtrace1.c:60)
==840756==    by 0x402B88: main (error_backtrace1.c:66)
==840756==  Address 0x74756f000a2e2e2e is not stack'd, malloc'd or (recently) free'd
```

**Comment by KavinduZoysa** [comment]
The original issue was we are getting more trace lines when optimizations are disabled and we do not change the trace start position. Therefore more trace lines are getting printed.
 
Since we know the expected number of trace lines, before we compare the trace, we can read the temp file (where actual trace lines are getting printed) one more time, get the number of lines and assert it with the expected number of lines.

@jclark, WDYT?

**Comment by jclark** [comment]
It would be better if the C code just printed out the backtrace: then the Makefile should use sed/diff etc to check whether the output is what is expected.

**Comment by KavinduZoysa** [comment]
> It would be better if the C code just printed out the backtrace: then the Makefile should use sed/diff etc to check whether the output is what is expected.

@jclark, to understand further what we have to do is, print the backtrace once without considering whether the optimizations are enabled or not, and check whether the expected trace(function name, file name and line number separately) is available or not. Is this correct?

**Comment by jclark** [comment]
Yes, make the C code as simple as possible, and do the rest of the work using something higher-level.
