### ISSUE TITLE
TypeDesc position errors

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#727]
The test cases in this commit

https://github.com/ballerina-platform/nballerina/commit/9f31c0ad25e5fa48753600f3e044f2e81efb2e35

caused some test failure relating to positions in testParserOnTestSuite, so I temporarily disabled that test.

After this is fixed, this should be reenabled.

**Comment by jclark** [comment]
We seem to get these kinds of issues quite often. Is the problem that the positions in the AST is wrong or is the problem with the testing code?

We need to get better error messages when the test fails.

Also I'm not sure if it was the `-fp` test that is causing the problems. Are these tests runs on `f` tests? If so, this should be changed.

**Comment by heshanpadmasiri** [comment]
In this case problem was caused a bug in testing code. For left recursions that we can't actually parse separately (parsing function will parse the whole thing instead of stopping with the child node) we have a workaround that check if the newly parsed node by the testing code has a child equal to the one given to it. Bug was it only checked it once when it should have checked repeatedly.
