### ISSUE TITLE
Implement function type descriptors and values

### ISSUE THREAD

**Issue by jclark** [ballerina-platform/nballerina#907]
At the moment, the only thing you can do with an identifier of a function definition is use it in a function call expression.

In this stage, we allow functions to be values, which can be (like other values):
- stored in variables
- passed as parameters
- returned from functions
- be the result of expressions

In this stage, the only way to create a function value is with a reference to the identifier of a function definition. Anonymous functions would be supported in #908.

The syntactic change is to support function type descriptors. (This is already implemented in semtypes.)

This also requires us to support casting a function value to another function type.

**Comment by jclark** [comment]
The main challenge here is dealing with the implications of variance for function types.

For example if I declare a function like this:

```
function foo() returns int {
  return 2;
}
```

it will return its value as an i64. But I can assign `foo` to a variable of type `function() returns any`.  When a function is called indirectly through this variable, the caller would expect to get the return value as a tagged pointer.

There is a similar problem (but the other way round) with arguments.

Note that exactness is relevant here. We can think of the declared type of the function definition as similar to the inherent type of a mutable structure.  If a reference to a function value is exact (the static type corresponds to the declared type), we can call the function directly like we do now.

**Comment by jclark** [comment]
Contravariance and varargs makes things difficult.

Consider

```
type F function(int, int);

function foo(F func, int arg1, int arg2) {
   return func(arg1, arg2);
}

function bar(int x, anydata... y) {
   io:println(x, ...y);
}

function baz(int x, int y) {
   foo(bar, x, y);
}
```

Since `[int, int]` is a subtype of `[int, anydata...]`, the type `function(int, anydata...)` is a subtype of `function(int, int)` (because of contravariance). So the value `bar` belongs to F. 

Ideally, we want to design things so that in `foo` (or any situation with an indirect function call) if the reference to `func` is exact, then it turns into calling via the function pointer without any additional processing of the arguments or return value. I suspect this will be hard to achieve.

**Comment by jclark** [comment]
The fundamental problem is that the representation of the arguments list of a function depends on the exact type of the function.  When making a direct call to a function this will be known. We will accordingly call this representation the direct representation. However in general when making an indirect call to a function having an argument list of type T, the caller knows only that the function has an argument list of type T' where the type system guarantees that T' is a subtype of T. (This is talking about the relationship between argument lists: for functions type is the subtyping is the other direction.)

In the above case, `foo` calls a function indirectly knowing it has argument list of type `[int, int]`, where the defined type of `foo` of the argument list is `[int, anydata...]`.

We can solve the problem by

- introducing another representation for argument lists that is uniform in the sense that the same argument list shape will be represented in the same way
- functions are still compiled assuming the direct representation for argument lists
- at the point where we turn the name of the function into a function value, we include in the function value a pointer to an additional function that can transform from the uniform representation of the argument list into the direct representation for this function
- at the point where we call the function value
    - we make use of another function that can transform from the direct representation for the static type of the function value into the uniform representation
    - we (optimistically) create the argument list in the direct representation form
    - we then check the exactness of the reference to the function value
    - if it is exact, then we call a pointer to the original function stored in the function value, which expects its arguments in direct format
    - otherwise
         - we call the function to transform the direct representation of the call site type into the uniform representation
         - this will in turn call the function stored in the function value to transform from the uniform representation to the direct representation of the function definition
         - this will in turn call the original function

Let's assume that we want to handle a direct varargs call in the obvious way, by having the caller build a list value for `...` parameter and then do a regular LLVM function call. With this approach, for the above example, we would at the LLVM level have the following functions

1. The normal function for bar. This would have two arguments: an i64 and a TaggedPointer referring to a mutable list with an inherent type of `anydata[]`,
2. The function to transform from uniform representation. This would take three arguments: a parameter count, a pointer  to an LLVM array of tagged pointers, and a function pointer to bar. It would construct a list value from all except the first member of the array, and the call the function pointer.
3. The function to transform to the uniform representation. This would take three arguments: two i64 arguments and pointer to the function value.  It would an array of length two on the stack create tagged pointers for both arguments, before calling the function to transform from the uniform representation.

**Comment by jclark** [comment]
Here's some C code with a rough sketch

```C
#include <stdlib.h>
#include <stdbool.h>
#include <stdint.h>

typedef void *Tagged;

struct FunctionPtr;

// I want the last arg here to be Indirect, but I am not sure how to do that in C
typedef Tagged (*Indirect)(int64_t argc, Tagged *argv, struct FunctionPtr *func);
typedef void *Direct; 

typedef struct FunctionPtr {
    Direct direct;
    Indirect indirect;
} *FunctionPtr;

extern void uniformArgsFromIntInt(int64_t x, int64_t y, FunctionPtr func);

typedef void (*FromIntIntFunc)(int64_t x, int64_t y, FunctionPtr func);

extern bool isExact(FunctionPtr func);

void foo(FunctionPtr func, int64_t arg1, int64_t arg2) {
    // This passes an extra argument to the direct function
    // (which is OK with C calling convention)
    FromIntIntFunc f = isExact(func) ? (FromIntIntFunc)func->direct: uniformArgsFromIntInt;
    f(arg1, arg2, func);
}

typedef void (*IntIntFunc)(int64_t x, int64_t y);

void foo2(FunctionPtr func, int64_t arg1, int64_t arg2) {
    if (isExact(func)) {
        ((IntIntFunc)(func->direct))(arg1, arg2);
    }
    else {
        uniformArgsFromIntInt(arg1, arg2, func);
    }
}

extern Tagged taggedFromInt(int64_t);
extern int64_t taggedToInt(Tagged);

void uniformArgsFromIntInt(int64_t x, int64_t y, FunctionPtr func) {
    Tagged args[2];
    args[0] = taggedFromInt(x);
    args[1] = taggedFromInt(y);
    (func->indirect)(2, args, func);
}

void uniformArgsToIntInt(int64_t argc, Tagged *argv, FunctionPtr func) {
    IntIntFunc direct = (IntIntFunc)(func->direct);
    direct(taggedToInt(argv[0]), taggedToInt(argv[1]));
}
```

foo and foo2 are different ways of doing the same thing: with foo we construct the arg list once but pass an extra arg to the direct function; with foo2 we construct the arg list twice. The former is less code, the latter is faster.

Note that the `uniformArgsToIntInt` and `uniformArgsFromIntInt` can be shared between functions types with the same representation.

**Comment by manuranga** [comment]
[Assembly instruction](https://godbolt.org/z/r5Tssv37G) count for foo and foo2 seems to be almost same size.

**Comment by heshanpadmasiri** [comment]
I plan to do this in two stages
1. Support function values without function type variance (functions types must be exactly same)
2. Add support for [variance of function types](https://github.com/ballerina-platform/nballerina/issues/907#issuecomment-1034444314)

**Comment by heshanpadmasiri** [comment]
@jclark this is my plan to implement stage 2 (function type variance) based on the design in [this comment](https://github.com/ballerina-platform/nballerina/issues/907#issuecomment-1041053503)

## Summary
1. Don’t change anything when it comes to directly calling function (`CallInsn`)
2. For `CallIndirectInsn` first check if the type of  `FunctionPtr` for the function value is exactly the same as the Function it points to
    1. If so we can use the same process as stage 1
    2. Else,
        1. Transform the arguments to the uniform representation (array of `TaggedPtrs`) (let’s call the result uniform arguments)
        2. Pass these uniform arguments and the `FunctionDefnPtr` to another function that will return an array of pointers to the “Exact arguments” (arguments in the form expected by the llvm function)
        3. Load individual arguments to llvm register using a combination of `GEP` and `load` instructions
        4. Now we can call the function same as (i)
        5. Convert the return value (using a function similar to one used in (a))

## Possible limitation we have to work around
1. I don’t think we can directly call the pointer to the llvm function from the runtime since we can’t cast the pointer to the proper type (I don’t think we can pass actual C type nor create types at runtime). This means we have to create the actual function call in the compile time (ie. It needs to be in the ll file)

## FunctionDefn and FunctionPtr

We will extend the current representation for function values to be,
```c
typedef void *FuncPtr; // This is the actual pointer of the llvm function. Since we don't need to deref this at runtime this should be enough

typedef struct FunctionDefn {
    FuncPtr ptr; // we already have this in stage 1
    FunctionTypeDesc td; // I haven't fully figured out how this should look like
} FunctionDefn, *FunctionDefnPtr;
typedef struct FunctionPtr {
    FunctionDefnPtr value;
    FunctionTypeDesc td;
} *FunctionPtr;

```
_Maybe we need a pointer to <code>uniformArgsToFuncArgs</code> (described in “Transforming uniform representation to exact representation”) in the structs as well_

Note that `FunctionDefn` is specific to the function. For example in the code below
```ts
type F function(int, int) returns int;
type F_bar function(int, any) returns int;

public function main() {
    F foo = foo;
    F_bar bar = foo;
}

function foo(int a, any b) returns int {
    return 5;
}
```
We will have a single global `FunctionDefn` that is shared by two `FunctionPtr`s (corresponding to `foo` and `bar` having different values for their `td`)


## IsExact
```c
bool _bal_is_function_exact(FunctionPtr val);
```
This function will check if the `td` in `FunctionPtr` is the same as the `td` in `FunctionDefn`

We can use the current implementation (stage 1) if the function returns' true'. Else 



1. Transform arguments to the “Uniform representation”
2. Transform that uniform representation to the specific representation (ie. arguments as expected by llvm function)
3. Then we can call the function as before (stage 1)
4. Change the return value

I am not sure if we can combine stages 1 and 2 


## Uniform representation

This is the arguments as a llvm array of `TaggedPtrs` 


### Transforming to uniform representation

This will take the list of arguments provided at call and turn them into an array of `TaggedPtrs` (not entirely sure if we can do this in the C side if not we will have to generate llvm ir for this)


### Transforming uniform representation to exact representation

We will have a runtime function (say `uniformArgsToFuncArgs`) that will take the array of `TaggedPtr`s and a `FunctionDefnPtr` and create an array of pointers where each pointer points to the correct llvm argument. (We are using an array of pointers because arguments may differ in size). Note that due to limitation 1 we can’t directly call the function ptr after this in the runtime. So instead this will return the pointer array

At compile time we know the type of this pointer array so we will use a combination of `GEP` and `load` instructions to load these arguments to llvm registers and call the `Functionptr` same as stage 1

## Things left to clarify
1. Handling var-args: I am not sure whether “transforming to uniform representation” needs to handle converting var-args to a list or not (if so it needs to be aware of the target function)
2. `FunctionTypeDesc`

**Comment by heshanpadmasiri** [comment]
@jclark API changes I think we need to support calling function values without a single explicit type (mostly this is unions but will also handle cases like else branch in type test) are as follows
1. The two* places I think need to change in #1191 are
    1. When generating BIR for function calls [here](https://github.com/heshanpadmasiri/nballerina/blob/86cf8dca32559c786c27dc79465dbb158c8c2a5b/compiler/modules/front/expr.bal#L1399)
    2. When generating LL for indirect calls [here](https://github.com/heshanpadmasiri/nballerina/blob/86cf8dca32559c786c27dc79465dbb158c8c2a5b/compiler/modules/nback/basic.bal#L234)
    3. We will need access to the same function for BIR validation
2. For both of these cases what I need is a function that generates a [`FunctionSignature`](https://github.com/heshanpadmasiri/nballerina/blob/86cf8dca32559c786c27dc79465dbb158c8c2a5b/compiler/modules/types/function.bal#L49) (at least all the information in a signature maybe with a different name if we are going to link "signature" with "function atom") for a given `SemType` (which is a subtype of `FUNCTION`)
3. For this I am thinking of adding a function to `function.bal` (in the `types` module) as,
```
public function complexFunctionSignature(Context cx, SemType ty) returns FunctionSignature?
```

I am not sure about the name for the moment I am using this to differentiate it from [`functionSignature`](https://github.com/heshanpadmasiri/nballerina/blob/86cf8dca32559c786c27dc79465dbb158c8c2a5b/compiler/modules/types/function.bal#L56) function. (I plan to keep `functionSignature` so we can use that when we already have a `FunctionAtomicType`)

I am planning to use this as the only function (i.e. without differentiating whether the function type is `Atomic` or not on the caller side) in instances mentioned in 1.

-  If the `semType` is not a proper subtype of `FUNCTION` it will return `()`.
-  If the `semType` is atomic it will use the current `functionSignature` directly
-  Else it will use the algorithm in section 4.4.3 in the paper to derive the corresponding parameter types and return type.

**Comment by heshanpadmasiri** [comment]
# Venn diagrams for complex test cases

![Untitled-2022-07-05-1129 (2)](https://github.com/ballerina-platform/nballerina/assets/17991461/aa4f836b-6916-45f5-ab4d-299591d0e160)
![Untitled-2022-07-05-1129 (1)](https://github.com/ballerina-platform/nballerina/assets/17991461/2b49ce82-1bdc-40c5-952a-74112dec842b)
![Untitled-2022-07-05-1129 (3)](https://github.com/ballerina-platform/nballerina/assets/17991461/2969efd5-8e4c-4b34-8519-9db138dcdb74)
