### ISSUE TITLE
Add filler values to tuples

### ISSUE THREAD

**Issue by ushirask** [ballerina-platform/nballerina#946]
When initializing a tuple or fixed length array with fewer members than the minimum required length, remaining members should be filled with filler values, if the rest type has a filler; otherwise this should be a compile-time error.

i.e. `int[3] a = [1, 2]` should be filled as `[1, 2, 0]`

**Comment by jclark** [comment]
Difficult case is something like this:

```
map<int>[1024] = [];
```

This constructs 1024 separate maps.

**Comment by jclark** [comment]
I think this implies it should be done in the backend.

Front-end checks whether member type is fillable. Back-end generates code to fill.

**Comment by jclark** [comment]
`fillableStructureBasicType` isn't doing the right thing for lists.

**Comment by jclark** [comment]
This is difficult because for lists a filling-get has to fill in members that are required, not just the members in `rest`. This is different from the situation with mappings. Records have defaults, so defaults are used to fill in required members; tuples don't have defaults, so instead filling is used to fill in required members.

The particular point that is difficult is filling in required structure members in a tuple, e.g. FillMember needs to work for members of T:

```
type T [int[], int[]][];
```

However, ListDesc currently only provides a single FillerDesc, which is for the rest member.

**Comment by jclark** [comment]
Recursive tuples can be both fillable `[int, T?]` and unfillable `[int, T]`.

**Comment by jclark** [comment]
See also https://github.com/ballerina-platform/ballerina-spec/issues/1064

**Comment by jclark** [comment]
There are several distinct uses of filling values:

1. when adding a new member to a list at some index i, we need to fill in the members between the old length and i; this requires creating members that belong to the rest type of that list
2. when a list constructor is constructing a list with tuple type, we need to fill in required members that were not specified in the list constructor 
3. when in 1, the rest-type is a tuple type, we may need to fill in values for the required members of that tuple

Note that

- case 1 uses only rest type, whereas case 2 and 3 may fill in other list members
- case 3 happens as part of case 1
- case 2 needs to do something similar to 3, when the tuple member is itself a list
- for case 2, we know which member is being filled in at compile time
- for case 3, we are filling in all the members of the tuple

**Comment by heshanpadmasiri** [comment]
closed with #1153
